availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/db-password/versions/latest
    env: 'DB_PASSWORD'

steps:
- name: 'hashicorp/terraform:latest'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    terraform init
    terraform plan \
      -var="project_id=$PROJECT_ID" \
      -var="db_password=$$DB_PASSWORD"

  secretEnv: ['DB_PASSWORD']

options:
  logging: CLOUD_LOGGING_ONLY