steps:
  #Terraform Init
  - name: "hashicorp/terraform:latest"
    id: "terraform init"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        terraform init

  #Terraform Plan
  - name: "hashicorp/terraform:latest"
    id: "terraform plan"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        terraform plan -input=false -var-file=terraform.tfvars

  #Terraform Apply
  - name: "hashicorp/terraform:latest"
    id: "terraform apply"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        terraform apply -input=false -auto-approve -var-file=terraform.tfvars

timeout: "1200s"