steps:
  - name: "hashicorp/terraform:latest"
    id: "init"
    entrypoint: "sh"
    args:
      - "-c"
      - "terraform init"

  - name: "hashicorp/terraform:latest"
    id: "plan"
    entrypoint: "sh"
    args:
      - "-c"
      - "terraform plan -input=false -var-file=terraform.tfvars"

  - name: "hashicorp/terraform:latest"
    id: "apply"
    entrypoint: "sh"
    args:
      - "-c"
      - "terraform apply -input=false -auto-approve -var-file=terraform.tfvars"

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "1200s"